apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "faucet.fullname" . }}-frontend-nem
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
data:
  env: |
    {{- .Values.config.frontend.nem.env | nindent 4 }}