apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "faucet.fullname" . }}-frontend-nem
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "faucet.selectorLabels" . | nindent 6 }}
      {{- toYaml .Values.deployments.frontend.nem.podLabels | nindent 6}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "faucet.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.deployments.frontend.nem.podLabels | nindent 8}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "faucet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.deployments.frontend.nem.image.repository }}:{{ .Values.deployments.frontend.nem.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployments.frontend.nem.image.pullPolicy }}
          ports:
            - name: fe-nem-port
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "faucet.fullname" . }}-frontend-nem
          livenessProbe:
            {{- toYaml .Values.deployments.frontend.nem.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.deployments.frontend.nem.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
