apiVersion: v1
kind: Service
metadata:
  name: {{ include "faucet.fullname" . }}-backend
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.backend.type }}
  ports:
    - port: {{ .Values.services.backend.port }}
      targetPort: backend-port
      protocol: TCP
      name: backend-port
  selector:
    {{- include "faucet.selectorLabels" . | nindent 4 }}
