apiVersion: v1
kind: Service
metadata:
  name: {{ include "faucet.fullname" . }}-authenticator
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.authenticator.type }}
  ports:
    - port: {{ .Values.services.authenticator.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "faucet.selectorLabels" . | nindent 4 }}
