apiVersion: v1
kind: Service
metadata:
  name: {{ include "faucet.fullname" . }}-authenticator
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.authenticator.type }}
  ports:
    - port: {{ .Values.services.authenticator.port }}
      targetPort: auth-port
      protocol: TCP
      name: auth-port
  selector:
    {{- include "faucet.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.deployments.authenticator.podLabels | nindent 4}}
